export const SOCKET_EVENTS = {
  ORDER_STATUS_CHANGED: 'ORDER_STATUS_CHANGED',
  TABLE_UPDATED: 'TABLE_UPDATED',
  NEW_ORDER: 'NEW_ORDER',
  ORDER_UPDATED: 'ORDER_UPDATED',
  ORDER_DELETED: 'ORDER_DELETED'
} as const; 