export const API_CONFIG = {
  BASE_URL: 'http://localhost:3002',
  CLIENT_URL: 'http://localhost:3000',
  SOCKET_URL: 'http://localhost:3002',
  TIMEOUT: 60000,
  HEADERS: {
    'Content-Type': 'application/json',
    Accept: 'application/json',
  },
} as const;

export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/api/auth/login',
    LOGIN_WITH_BRANCH: '/api/auth/login/branch',
    REGISTER: '/api/auth/register',
    LOGOUT: '/api/auth/logout',
    REFRESH_TOKEN: '/api/auth/refresh',
    ME: '/api/auth/me',
    FORGOT_PASSWORD: '/api/auth/forgot-password',
    RESET_PASSWORD: '/api/auth/reset-password',
    BRANCHES: '/api/auth/branches'
  },
  ACCOUNTS: {
    LIST: '/api/accounts',
    DETAIL: (id: string) => `/api/accounts/${id}`,
    CREATE: '/api/accounts',
    UPDATE: (id: string) => `/api/accounts/${id}`,
    DELETE: (id: string) => `/api/accounts/${id}`,
    TRANSACTIONS: {
      LIST: (accountId: string) => `/api/accounts/transactions/account/${accountId}`,
      CREATE: '/api/accounts/transactions'
    }
  },
  BRANCHES: {
    LIST: '/api/branches',
    DETAIL: (id: string) => `/api/branches/${id}`,
    CREATE: '/api/branches',
    UPDATE: (id: string) => `/api/branches/${id}`,
    DELETE: (id: string) => `/api/branches/${id}`,
    SETTINGS: (id: string) => `/api/branches/${id}/settings`,
  },
  BAR: {
    ORDERS: '/api/bar/orders',
    ORDER_STATUS: (id: string) => `/api/bar/orders/${id}/status`,
    QUEUE: '/api/bar/queue',
    STATS: '/api/bar/stats'
  },
  KITCHEN: {
    ORDERS: '/api/kitchen/orders',
    ORDER_STATUS: (id: string) => `/api/kitchen/orders/${id}/status`,
    ORDER_NOTES: (id: string) => `/api/kitchen/orders/${id}/notes`,
    QUEUE: '/api/kitchen/queue',
    STATS: '/api/kitchen/stats',
    RECIPE: (productId: string) => `/api/kitchen/recipe/${productId}`
  },
  PRODUCTS: {
    LIST: '/api/products',
    DETAIL: (id: string) => `/api/products/${id}`,
    CREATE: '/api/products',
    UPDATE: (id: string) => `/api/products/${id}`,
    DELETE: (id: string) => `/api/products/${id}`,
    STATUS: (id: string) => `/api/products/${id}/status`,
    STOCK: (id: string) => `/api/products/${id}/stock`,
    OPTIONS: (id: string) => `/api/products/${id}/options`,
    PRICE_HISTORY: (id: string) => `/api/products/${id}/price-history`,
    VARIANTS: (id: string) => `/api/products/${id}/variants`,
    ADD_VARIANT: (id: string) => `/api/products/${id}/variants`,
    UPDATE_VARIANT: (id: string, variantId: string) => `/api/products/${id}/variants/${variantId}`,
    DELETE_VARIANT: (id: string, variantId: string) => `/api/products/${id}/variants/${variantId}`,
    ADD_OPTION_GROUP: (id: string) => `/api/products/${id}/options/groups`,
    ADD_OPTION: (id: string) => `/api/products/${id}/options`,
    UPDATE_OPTION: (id: string, optionId: string) => `/api/products/${id}/options/${optionId}`,
    DELETE_OPTION: (id: string, optionId: string) => `/api/products/${id}/options/${optionId}`,
    DELETE_OPTION_GROUP: (productId: string, groupId: string) => `/api/products/${productId}/options/groups/${groupId}`,
  },
  STOCKS: {
    LIST: '/api/stocks',
    DETAIL: (id: string) => `/api/stocks/${id}`,
    HISTORY: (id: string) => `/api/stocks/${id}/history`,
    UPDATE_QUANTITY: (id: string) => `/api/stocks/${id}/quantity`,
    MOVEMENTS: '/api/stocks/movements',
    EXPIRING: '/api/stocks/expiring',
    TRANSFER: '/api/stocks/transfer',
    COUNT: '/api/stocks/count',
    LOW: '/api/stocks/low',
  },
  ORDERS: {
    LIST: '/api/orders',
    DETAIL: (id: string) => `/api/orders/${id}`,
    CREATE: '/api/orders',
    UPDATE: (id: string) => `/api/orders/${id}`,
    DELETE: (id: string) => `/api/orders/${id}`,
    STATUS: (id: string) => `/api/orders/${id}/status`,
    NOTES: (id: string) => `/api/orders/${id}/notes`,
    BY_TABLE: (tableId: string) => `/api/orders/table/${tableId}`,
    BY_WAITER: (waiterId: string) => `/api/orders/waiter/${waiterId}`,
    BY_CUSTOMER: (customerId: string) => `/api/orders/customer/${customerId}`,
    BY_BRANCH: (branchId: string) => `/api/orders/branch/${branchId}`,
    BY_STATUS: (status: string) => `/api/orders/status/${status}`,
    BY_DATE_RANGE: '/api/orders/date-range',
    BULK_DELETE: '/api/orders/bulk-delete',
    BULK_STATUS: '/api/orders/bulk-status',
    PRINT: '/api/orders/print'
  },
  TABLES: {
    LIST: '/api/tables',
    DETAIL: (id: string) => `/api/tables/${id}`,
    CREATE: '/api/tables',
    UPDATE: (id: string) => `/api/tables/${id}`,
    DELETE: (id: string) => `/api/tables/${id}`,
    STATUS: (id: string) => `/api/tables/${id}/status`,
    MERGE: '/api/tables/merge',
    TRANSFER: '/api/tables/transfer',
    BY_BRANCH: (branchId: string) => `/api/tables/branch/${branchId}`
  },
  CUSTOMERS: {
    LIST: '/api/customers',
    DETAIL: (id: string) => `/api/customers/${id}`,
    CREATE: '/api/customers',
    UPDATE: (id: string) => `/api/customers/${id}`,
    DELETE: (id: string) => `/api/customers/${id}`,
    ORDERS: (id: string) => `/api/customers/${id}/orders`,
    RESERVATIONS: (id: string) => `/api/customers/${id}/reservations`,
    SEARCH: '/api/customers/search'
  },
  CATEGORIES: {
    LIST: '/api/categories',
    DETAIL: (id: string) => `/api/categories/${id}`,
    CREATE: '/api/categories',
    UPDATE: (id: string) => `/api/categories/${id}`,
    DELETE: (id: string) => `/api/categories/${id}`,
  },
  RECIPES: {
    LIST: '/api/recipes',
    DETAIL: (id: string) => `/api/recipes/${id}`,
    CREATE: '/api/recipes',
    UPDATE: (id: string) => `/api/recipes/${id}`,
    DELETE: (id: string) => `/api/recipes/${id}`,
    BY_PRODUCT: (productId: string) => `/api/recipes/product/${productId}`,
    CALCULATE_COST: (id: string) => `/api/recipes/${id}/cost`,
    VERSIONS: (id: string) => `/api/recipes/${id}/versions`,
    DUPLICATE: (id: string) => `/api/recipes/${id}/duplicate`,
    BULK_UPDATE_INGREDIENTS: (id: string) => `/api/recipes/${id}/ingredients`,
    COMPARE: '/api/recipes/compare',
  },
  SUPPLIERS: {
    LIST: '/api/suppliers',
    DETAIL: (id: string) => `/api/suppliers/${id}`,
    CREATE: '/api/suppliers',
    UPDATE: (id: string) => `/api/suppliers/${id}`,
    DELETE: (id: string) => `/api/suppliers/${id}`,
    PRODUCTS: (id: string) => `/api/suppliers/${id}/products`,
    ADD_PRODUCT: (id: string) => `/api/suppliers/${id}/products`,
    BY_PRODUCT: (productId: string) => `/api/products/${productId}/suppliers`,
  },
} as const;