export const API_CONFIG = {
  BASE_URL: 'http://localhost:3002/api',
  TIMEOUT: 60000,
  HEADERS: {
    'Content-Type': 'application/json',
    Accept: 'application/json',
  },
} as const;

export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    LOGIN_WITH_BRANCH: '/auth/login/branch',
    REGISTER: '/auth/register',
    LOGOUT: '/auth/logout',
    REFRESH_TOKEN: '/auth/refresh',
    ME: '/auth/me',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
  },
  PRODUCTS: {
    LIST: '/products',
    DETAIL: (id: string) => `/products/${id}`,
    CREATE: '/products',
    UPDATE: (id: string) => `/products/${id}`,
    DELETE: (id: string) => `/products/${id}`,
    STATUS: (id: string) => `/products/${id}/status`,
    STOCK: (id: string) => `/products/${id}/stock`,
    OPTIONS: (id: string) => `/products/${id}/options`,
    PRICE_HISTORY: (id: string) => `/products/${id}/price-history`,
    VARIANTS: (id: string) => `/products/${id}/variants`,
    ADD_VARIANT: (id: string) => `/products/${id}/variants`,
    UPDATE_VARIANT: (id: string, variantId: string) => `/products/${id}/variants/${variantId}`,
    DELETE_VARIANT: (id: string, variantId: string) => `/products/${id}/variants/${variantId}`,
    ADD_OPTION_GROUP: (id: string) => `/products/${id}/options/groups`,
    ADD_OPTION: (id: string) => `/products/${id}/options`,
    UPDATE_OPTION: (id: string, optionId: string) => `/products/${id}/options/${optionId}`,
    DELETE_OPTION: (id: string, optionId: string) => `/products/${id}/options/${optionId}`,
    DELETE_OPTION_GROUP: (productId: string, groupId: string) => `/products/${productId}/options/groups/${groupId}`,
  },
  STOCKS: {
    LIST: '/stocks',
    DETAIL: (id: string) => `/stocks/${id}`,
    HISTORY: (id: string) => `/stocks/${id}/history`,
    UPDATE_QUANTITY: (id: string) => `/stocks/${id}/quantity`,
    MOVEMENTS: '/stocks/movements',
    EXPIRING: '/stocks/expiring',
    TRANSFER: '/stocks/transfer',
    COUNT: '/stocks/count',
    LOW: '/stocks/low',
  },
  ORDERS: {
    LIST: '/orders',
    DETAIL: (id: string) => `/orders/${id}`,
    CREATE: '/orders',
    UPDATE: (id: string) => `/orders/${id}`,
    DELETE: (id: string) => `/orders/${id}`,
    CANCEL: (id: string) => `/orders/${id}/cancel`,
    STATUS: (id: string) => `/orders/${id}/status`,
    BULK_DELETE: '/orders/bulk-delete',
    BULK_STATUS: '/orders/bulk-status',
    PRINT: '/orders/print',
    ADD_ITEMS: (id: string) => `/orders/${id}/items`,
  },
  TABLES: {
    LIST: '/tables',
    DETAIL: (id: string) => `/tables/${id}`,
    CREATE: '/tables',
    UPDATE: (id: string) => `/tables/${id}`,
    DELETE: (id: string) => `/tables/${id}`,
    STATUS: (id: string) => `/tables/${id}/status`,
  },
  CUSTOMERS: {
    LIST: '/customers',
    DETAIL: (id: string) => `/customers/${id}`,
    CREATE: '/customers',
    UPDATE: (id: string) => `/customers/${id}`,
    DELETE: (id: string) => `/customers/${id}`,
    ORDERS: (id: string) => `/customers/${id}/orders`,
    RESERVATIONS: (id: string) => `/customers/${id}/reservations`,
  },
  CATEGORIES: {
    LIST: '/categories',
    DETAIL: (id: string) => `/categories/${id}`,
    CREATE: '/categories',
    UPDATE: (id: string) => `/categories/${id}`,
    DELETE: (id: string) => `/categories/${id}`,
  },
  RECIPES: {
    LIST: '/recipes',
    DETAIL: (id: string) => `/recipes/${id}`,
    CREATE: '/recipes',
    UPDATE: (id: string) => `/recipes/${id}`,
    DELETE: (id: string) => `/recipes/${id}`,
    BY_PRODUCT: (productId: string) => `/recipes/product/${productId}`,
    CALCULATE_COST: (id: string) => `/recipes/${id}/cost`,
    VERSIONS: (id: string) => `/recipes/${id}/versions`,
    DUPLICATE: (id: string) => `/recipes/${id}/duplicate`,
    BULK_UPDATE_INGREDIENTS: (id: string) => `/recipes/${id}/ingredients`,
    COMPARE: '/recipes/compare',
  },
} as const;