export const API_CONFIG = {
  BASE_URL: 'http://localhost:3002/api',
  TIMEOUT: 30000,
  HEADERS: {
    'Content-Type': 'application/json',
    Accept: 'application/json',
  },
} as const;

export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    LOGIN_WITH_BRANCH: '/auth/login/branch',
    REGISTER: '/auth/register',
    LOGOUT: '/auth/logout',
    REFRESH_TOKEN: '/auth/refresh',
    ME: '/auth/me',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
  },
  PRODUCTS: {
    LIST: '/products',
    DETAIL: (id: string) => `/products/${id}`,
    CREATE: '/products',
    UPDATE: (id: string) => `/products/${id}`,
    DELETE: (id: string) => `/products/${id}`,
    STATUS: (id: string) => `/products/${id}/status`,
    STOCK: (id: string) => `/products/${id}/stock`,
    OPTIONS: (id: string) => `/products/${id}/options`,
  },
  ORDERS: {
    LIST: '/orders',
    DETAIL: (id: string) => `/orders/${id}`,
    CREATE: '/orders',
    UPDATE: (id: string) => `/orders/${id}`,
    DELETE: (id: string) => `/orders/${id}`,
    CANCEL: (id: string) => `/orders/${id}/cancel`,
    STATUS: (id: string) => `/orders/${id}/status`,
    BULK_DELETE: '/orders/bulk-delete',
    BULK_STATUS: '/orders/bulk-status',
    PRINT: '/orders/print',
    ADD_ITEMS: (id: string) => `/orders/${id}/items`,
  },
  TABLES: {
    LIST: '/tables',
    DETAIL: (id: string) => `/tables/${id}`,
    CREATE: '/tables',
    UPDATE: (id: string) => `/tables/${id}`,
    DELETE: (id: string) => `/tables/${id}`,
    STATUS: (id: string) => `/tables/${id}/status`,
  },
  CUSTOMERS: {
    LIST: '/customers',
    DETAIL: (id: string) => `/customers/${id}`,
    CREATE: '/customers',
    UPDATE: (id: string) => `/customers/${id}`,
    DELETE: (id: string) => `/customers/${id}`,
    ORDERS: (id: string) => `/customers/${id}/orders`,
    RESERVATIONS: (id: string) => `/customers/${id}/reservations`,
  },
} as const;